# Generated by Django 3.2.7 on 2021-10-22 12:42

from django.db import migrations, models
import nanoid.generate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField(verbose_name='original_link_url')),
                ('shortened_token', models.TextField(default=nanoid.generate, max_length=8, unique=True, verbose_name='shortened_url_token')),
                ('views', models.IntegerField(default=0, verbose_name='link_views')),
            ],
        ),
    ]
